# Generated by Django 4.2.4 on 2023-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_ticket_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
