# Generated by Django 4.2.4 on 2023-09-05 14:27

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
