# Generated by Django 4.2.4 on 2023-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_airplane_airplane_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="closest_big_cite",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
