# Generated by Django 4.2.4 on 2023-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0010_alter_route_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(blank=True, null=True, to="airport.crew"),
        ),
    ]
